mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.nana.port.payload
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    password: coffee
    url: jdbc:log4jdbc:mysql://localhost:3306/triz?serverTimezone=UTC&characterEncoding=UTF-8
    username: seumudal
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
